/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package homes ;
import connections.DB_Access;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class Manu_Update extends javax.swing.JFrame {

    private DB_Access dba;
    private DefaultTableModel def_manu;
    /**
     * Creates new form Menu_Update
     */
    public Manu_Update() {
        initComponents();
        clear_data();
        def_manu=new DefaultTableModel(){
            
        @Override
        public boolean isCellEditable(int row, int column) {
            //all cells false
            return false;
        }
         
        };
        
        def_manu.addColumn("Item");
        def_manu.addColumn("Style");
        def_manu.addColumn("Type");
        def_manu.addColumn("Quantity");
        def_manu.addColumn("Portion");
        def_manu.addColumn("Price");
    
        fill_table();
        tbl_Manu.setModel(def_manu);
        btn_save_changes.setEnabled(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Manu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_item = new javax.swing.JTextField();
        txt_type = new javax.swing.JTextField();
        txt_style = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        txt_portion = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        btn_edit_row = new javax.swing.JButton();
        btn_delete_row = new javax.swing.JButton();
        btn_save_changes = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        tbl_Manu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Manu.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_Manu);

        jLabel1.setText("Item");

        jLabel2.setText("Type");

        jLabel3.setText("Style");

        txt_item.setEditable(false);
        txt_item.setText("jTextField1");

        txt_type.setEditable(false);
        txt_type.setText("jTextField2");

        txt_style.setEditable(false);
        txt_style.setText("jTextField3");

        jLabel4.setText("Quantity");

        jLabel5.setText("Portion");

        jLabel6.setText("Price");

        txt_quantity.setEditable(false);
        txt_quantity.setText("jTextField1");

        txt_portion.setEditable(false);
        txt_portion.setText("jTextField2");

        txt_price.setText("jTextField3");

        btn_edit_row.setText("Edit Row");
        btn_edit_row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_rowActionPerformed(evt);
            }
        });

        btn_delete_row.setText("Delete Row");
        btn_delete_row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_rowActionPerformed(evt);
            }
        });

        btn_save_changes.setText("Save Changes");
        btn_save_changes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_changesActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("UPDATE MENUE");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\final12345 project\\src\\homes\\eeeeeeee.jpg")); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_save_changes)
                                .addGap(253, 253, 253))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_edit_row)
                                .addGap(116, 116, 116)
                                .addComponent(btn_delete_row)
                                .addGap(197, 197, 197))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(txt_item, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_style, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_portion, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(120, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addGap(75, 75, 75)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel8)))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_portion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_style, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_delete_row)
                            .addComponent(btn_edit_row))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btn_save_changes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(751, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_edit_rowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_rowActionPerformed
        // TODO add your handling code here:
        int row=tbl_Manu.getSelectedRow();
        
        if(!isValidRow(row,"Please select a row\n to edit","EDIT ROW"))
            return;
        
        btn_edit_row.setEnabled(false);
        btn_delete_row.setEnabled(false);
        btn_save_changes.setEnabled(true);
        
        txt_item.setText(tbl_Manu.getValueAt(row, 0).toString());
        txt_portion.setText(tbl_Manu.getValueAt(row, 4).toString());
        txt_price.setText(tbl_Manu.getValueAt(row, 5).toString());
        txt_quantity.setText(tbl_Manu.getValueAt(row, 3).toString());
        txt_style.setText(tbl_Manu.getValueAt(row, 2).toString());
        txt_type.setText(tbl_Manu.getValueAt(row, 1).toString());
        
    }//GEN-LAST:event_btn_edit_rowActionPerformed

    private void btn_save_changesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_changesActionPerformed
        // TODO add your handling code here:
       
        String newPrice=txt_price.getText().trim().toString();
        int row=tbl_Manu.getSelectedRow();
        
        if(!isValidRow(row,"",""))
            return;
        
        if(txt_price.getText().toString().equals(tbl_Manu.getValueAt(row, 5).toString()))
        {
            JOptionPane.showMessageDialog(rootPane, "You haven't change\nthe value...", "PRICE", 1);
            return;
        }
        if(!isNum(newPrice))
        {
            JOptionPane.showMessageDialog(rootPane, "Price must not \nbe letters...", "ERROR", 0);
            return;
        }
              
        try
        {
            dba.setData("update menu6 set price="+ newPrice +" where item='"+ tbl_Manu.getValueAt(row, 0).toString() 
                        +"' && style='"+ tbl_Manu.getValueAt(row, 2).toString() +"' && type='"+ tbl_Manu.getValueAt(row, 1).toString() 
                        +"' && Quantity="+ tbl_Manu.getValueAt(row, 3).toString() +" && portion ='"+ tbl_Manu.getValueAt(row, 4).toString() 
                        +"' && price="+ tbl_Manu.getValueAt(row, 5).toString());
            
            JOptionPane.showMessageDialog(rootPane, "Successfully updated...", "MENU UPDATE", 1);
            def_manu.setRowCount(0);
            fill_table();
        }
        catch(Exception ex)
        {
            System.out.println("ERROR :" + ex.toString());
        }
        
        btn_save_changes.setEnabled(false);
        btn_edit_row.setEnabled(true);
        btn_delete_row.setEnabled(true);
        clear_data();
    }//GEN-LAST:event_btn_save_changesActionPerformed

    private void btn_delete_rowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_rowActionPerformed
        // TODO add your handling code here:
        int row=tbl_Manu.getSelectedRow();
        
        if(!isValidRow(row,"Please select a row\n to delete","DELETE ROW"))
            return;
        
        int option=JOptionPane.showConfirmDialog(rootPane, "Are you sure...?", "DELETE ROW", 0);
        
        if(option==JOptionPane.YES_OPTION)
        {
            try
            {
                dba.setData("delete from menu6 where item='"+ tbl_Manu.getValueAt(row, 0).toString() 
                        +"' && style='"+ tbl_Manu.getValueAt(row, 2).toString() +"' && type='"+ tbl_Manu.getValueAt(row, 1).toString() 
                        +"' && Quantity="+ tbl_Manu.getValueAt(row, 3).toString() +" && portion ='"+ tbl_Manu.getValueAt(row, 4).toString() 
                        +"' && price="+ tbl_Manu.getValueAt(row, 5).toString());
                JOptionPane.showMessageDialog(rootPane, "Row is remove from\nthe table...", "SUCCESSFULLY REMOVED", 1);
                
                def_manu.setRowCount(0);
                fill_table();
            }
            catch(Exception ex)
            {
                System.out.println("ERROR :" + ex.toString());
                JOptionPane.showMessageDialog(rootPane, "Currently this menu is\nusing... ", "REMOVE MENU", 0);
            }
        }
        
        else
        {
            return;
        }
        
    }//GEN-LAST:event_btn_delete_rowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manu_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manu_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manu_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manu_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manu_Update().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete_row;
    private javax.swing.JButton btn_edit_row;
    private javax.swing.JButton btn_save_changes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Manu;
    private javax.swing.JTextField txt_item;
    private javax.swing.JTextField txt_portion;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_style;
    private javax.swing.JTextField txt_type;
    // End of variables declaration//GEN-END:variables

private void fill_table()
{
   
    try{
        ResultSet rs=dba.getData("select * from menu6");
            while(rs.next()){
                def_manu.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)});
                System.out.println(rs.getString(1));
            }
        }
        catch(NullPointerException e){
            System.out.println(e.getMessage());
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
}

private void clear_data()
{
    txt_item.setText("");
    txt_portion.setText("");
    txt_price.setText("");
    txt_quantity.setText("");
    txt_style.setText("");
    txt_type.setText("");
}

private boolean isNum(String ch)
    {
        boolean status=true;
        try
        {
            int x=Integer.parseInt(ch);
        }
        
        catch(Exception ex)
        {
            status=false;
        }
        return status;
    }

private boolean isValidRow(int row,String error,String e_header)
{
    if(row<0)
        {
            JOptionPane.showMessageDialog(rootPane, error,e_header,0);
            return false;
        }
    return true;
}
}